---
title: Project Review Part 5 
author: Mutsa Nyamuranga
date: 04-25-2024
format: 
  html:
    toc: true
    toc-depth: 3
    number-sections: true
---

# Overview

Title of project: Survival Analysis of Males in the U.S. with Prostate Cancer Based on Race and Ethnicity

Name of project author(s): Ranni Tewfik

Name of project reviewer: Mutsa Nyamuranga


# Instructions

# Specific project content evaluation
Evaluate the different parts of the project by filling in the sections below.


## Background, Context and Motivation
How well is the context of the project described? Is a comprehensive background, including summary of previous/related work given? Is the project well placed into the context of existing work (including proper referencing of existing work). Is it clear why the project was undertaken and what new information it hopes to provide?

### Feedback and Comments

The background was very thorough with multiple citations and necessary cotextual evidence. 

### Summary assessment (PICK ONE, DELETE THE OTHERS)

* strong contextualization and motivation



## Question description
How well and clear are the question(s)/hypotheses the project aims to address described? Is it clear how the questions relate to the data?


### Feedback and Comments

The research question was clearly stated and explained. 

### Summary assessment

* question/hypotheses fully clear



## Data description
How well is the data overall described? Is the source provided? Is a codebook or other meta-information available that makes it clear what the data is? 

### Feedback and Comments

Data source was clearly described. There was no codebook provided.   

### Summary assessment

* source and overall structure of data well explained


## Data wrangling and exploratory analysis
How well is the data cleaned/processed and explored? Are all steps reasonable and well explained? Are alternatives discussed and considered? Are meaningful exploratory results shown (e.g. in the supplementary materials)?

### Feedback and Comments

Data was well processed. Detailed comments/notes were provided for all procedures.
There was supplementary material provided. The was no Rdm (ReadMe) files provided. 

### Summary assessment

* essentially no weaknesses in wrangling and exploratory component

## Appropriateness of Analysis
Were the analysis methods appropriate for the data? Was the analysis done properly? Were different components of the analysis (e.g. performance measure, variable selection, data pre-processing, model evaluation) done in the best way possible and explained well?

### Feedback and Comments

The analysis methods were appropriate for the question to be answered. Cross-validation was used for tuning, performance evaluation and there were multiple models produced and tested to gather the appropriate metrics.

### Summary assessment

* strong and reasonable analysis

## Presentation
How well are results presented? Are tables and figures easy to read and understand? Are the main figures/tables publication level quality? 

### Feedback and Comments

The results were presented in a well-structured manner. 

### Summary assessment

* results are very well presented


## Discussion/Conclusions
Are the study findings properly discussed? Are strengths and limitations acknowledged? Are findings interpreted properly?

### Feedback and Comments

The statistical methods that were conducted could have been expanded upon. The strengths were presented but not expanded upon as well, but still a concise description of the project.

### Summary assessment

* minor parts wrong, missing or unclear


## Further comments

I think just overall, expand upon the discussion section. 



# Overall project content evaluation
Evaluate overall features of the project  by filling in the sections below.


## Structure
Is the project well structured? Are files in well labeled folders? Do files have reasonable names? Are all "junk" files not needed for analysis/reproduction removed? By just looking at files and folders, can you get an idea of how things fit together?

### Feedback and Comments

Well done in structuring the project. Everything is very clean and there are no unneccessary files. 

### Summary assessment

* well structured


## Documentation 
How well is the project documented? Are you able to understand each step of the whole analysis, each decision that was made, and each line of code? Is enough information provided as comments in code or as part of Rmd files? 

### Feedback and Comments

The description of code was well documented. I think the ReadMe files may have added more context to each folders purpose. 

### Summary assessment

* fully and well documented


## Reproducibility
Are all results fully reproducible? Is documentation provided which clearly explains how to reproduce things, and does it work without the need for any manual intervention? Are you able to re-run the whole analysis without having to do manual interventions/edits?

### Feedback and Comments

Everything runs good and in a reproducible way. Some chunks take a while to load as there is a lot of data being run through it, so possibly find a way to minimize the run time. 


### Summary assessment

* fully reproducible without issues


## Thoroughness
How thorough was the overall study? Were alternatives (e.g. different ways of processing the data or different models) considered? Were alternatives discussed? Were the questions/hypotheses fully and thoroughly addressed?

### Feedback and Comments

The main question was answered but the discussion could be more thorough. Overall, a complete project. 

### Summary assessment

* strong level of thorougness


## Further comments

This project is very comprehensive and answer the main question well. Small edits will clean it up but it is essentially complete. 